---
provider: 
- "SunLife"

string_match: 
    title_name: 
    - "by Amount Paid" 
    - "by Number of Claims"
    start_page: "1"
    match_regex: "/.*/"

extracts: 
    flavour: "stream"

schema_dict:
    num_cols: 7
    checks: 
        StringError : "contains_new_line"

fix_ups: 
    StringError: "rank_din_fix"

template_map: 
    src: "Renewal Template Proof Zero.xlsm"
    dst: "output.xlsm"