---
provider: 
- "SunLife"

string_match: 
    title_name: "PayDirect and Reimbursement Drugs Combined"
    start_page: "1"
    match_regex: "/.*/"

extracts: 
    flavour: "stream"

schema_dict:
    num_cols: 7
    checks: 
        StringError : "contains_new_line"

fix_ups: 
    StringError: "no_fix_up"

template_map: 
    src: "Renewal Template Proof Zero.xlsm"
    dst: "output.xlsm"