---
provider: "Sun Life"

tables:
- drug_claims:
    start_page: 1
    string_match: 
        title_name: "by Number of Claims"

    extracts: 
        flavour: "stream"
        sparse_filter: 0.75

    schema_dict:
        num_cols: 9
        checks: 
            StringError: "contains_new_line"
            column_in_dataframe: "pass"

    fix_ups: 
        StringError: "rank_din_fix"
        column_in_dataframe: "no_fix"

    template_map: 
        src: "Renewal Template Proof Zero.xlsm"
        dst_book: "top_dins.xlsx"
        dst_sheet: "DIN List"

- drugs_combined:
    start_page: 1
    string_match: 
        title_name: "Drug Claims Paid by Classification"

    extracts: 
        flavour: "stream"
        sparse_filter: 0.1

    schema_dict:
        num_cols: 5
        checks: 
            StringError: "contains_new_line"

    fix_ups: 
        StringError: "no_fix"

    template_map: 
        src: "Renewal Template Proof Zero.xlsm"
        dst_book: "classification.xlsx"
        dst_sheet: "Drug Claims"

- experience_analysis:
    string_match: 
        start_page: 16
        title_name: "Extended health care experience analysis"

    extracts: 
        flavour: "stream"
        sparse_filter: 0.1

    schema_dict:
        num_cols: 5
        checks: 
            StringError : "contains_new_line"

    fix_ups: 
        StringError : "no_fix"

    template_map: 
        src: "Renewal Template Proof Zero.xlsm"
        dst_book: "experience.xlsx"
        dst_sheet: "Analysis"
