---
provider: 
- "SunLife"
- "ManuLife"

string_match: 
    title_name: "by Number of Claims"
    start_page: "1"
    match_regex: "/.*/"

extracts: 
    flavour: "lattice"

schema: #needs to be a dictionary

fixups: 
    TableShapeSchemaError: "my_dinrank_fixup.py"

template_map: 
    src: "xyz"
    dst: "abc"